force-app/main/default/objects/SMKSearchResults__c/SMKSearchResults__c.object-meta.xml
<CustomObject>
    <label>SMKSearchResult</label>
    <nameField>
        <displayFormat>SR-{000}</displayFormat>
        <label>SMKSearchResults Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SearchResult</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMKSearchResults__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <label>Facility</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMKSearchResults__c/fields/MPIIID__c.field-meta.xml
<CustomField>
    <fullName>MPIIID__c</fullName>
    <label>MPIIID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMKSearchResults__c/fields/MRN__c.field-meta.xml
<CustomField>
    <fullName>MRN__c</fullName>
    <label>MRN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMKSearchResults__c/fields/Prefix__c.field-meta.xml
<CustomField>
    <fullName>Prefix__c</fullName>
    <label>Prefix</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMKSearchResults__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMKSearchResults__c/fields/Telephone__c.field-meta.xml
<CustomField>
    <fullName>Telephone__c</fullName>
    <label>Telephone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SMKSearchPatientFlow.cls
global class SMKSearchPatientFlow {
   @InvocableMethod
   public static void getAccountIds(List<String> Name) {
       SMKPatientService TheService = new SMKPatientService();
      List<SMKSearchPatient> ThePatients;
       
      ThePatients = TheService.SearchPatient('', Name[0], '');
       
      List<SMKSearchResults__c> Results = [select id from SMKSearchResults__c];
       
      delete Results;
       
      Results = new List<SMKSearchResults__c>();
      for (SMKSearchPatient Patient : ThePatients)
      {
          SMKSearchResults__c Result = new SMKSearchResults__c();
          
          Result.Facility__c = Patient.Facility;
          Result.FirstName__c = Patient.FirstName;
          Result.LastName__c = Patient.LastName;
          Result.MPIIID__c  = Patient.MPIID;
          Result.Prefix__c = Patient.Prefix;
          Result.Sex__c = Patient.Sex;
          Result.Telephone__c = Patient.Telephone;      
          Result.MRN__c = Patient.MRN;
          
          Results.add(Result);
      }
       
      Insert Results;

   }
}