force-app/main/default/objects/SMKSearchResults__c/SMKSearchResults__c.object-meta.xml
<CustomObject>
    <label>SMKSearchResult</label>
    <nameField>
        <displayFormat>SR-{000}</displayFormat>
        <label>SMKSearchResults Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SearchResult</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMKSearchResults__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <label>Facility</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMKSearchResults__c/fields/MPIIID__c.field-meta.xml
<CustomField>
    <fullName>MPIIID__c</fullName>
    <label>MPIIID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMKSearchResults__c/fields/MRN__c.field-meta.xml
<CustomField>
    <fullName>MRN__c</fullName>
    <label>MRN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMKSearchResults__c/fields/Prefix__c.field-meta.xml
<CustomField>
    <fullName>Prefix__c</fullName>
    <label>Prefix</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMKSearchResults__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMKSearchResults__c/fields/Telephone__c.field-meta.xml
<CustomField>
    <fullName>Telephone__c</fullName>
    <label>Telephone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SMKPatientFlow.cls
global class SMKPatientFlow implements Process.Plugin { 

   global Process.PluginResult invoke(Process.PluginRequest request) { 
      String MPIID = (String) request.inputParameters.get('MPIID');
      String LastName = (String) request.inputParameters.get('LastName');
      String Telephone = (String) request.inputParameters.get('Telephone'); 
       
      SMKPatientService TheService = new SMKPatientService();
      List<SMKSearchPatient> ThePatients;
       
       
      Database.query('delete [select id from SMKSearchResult__c limit 10000]');
       
      ThePatients = TheService.SearchPatient(MPIID, LastName, Telephone);
       
      List<SMKSearchResults__c> Results = new List<SMKSearchResults__c>();
      for (SMKSearchPatient Patient : ThePatients)
      {
          SMKSearchResults__c Result = new SMKSearchResults__c();
          
		
          //HealthCloudGA.HcPatient mypatient = new HealthCloudGA.HcPatient();
          //mypatient.PatientClass = 'Individual';
          //HealthCloudGA.PatientService.createPatient(mypatient);
          
          Result.Facility__c = Patient.Facility;
          Result.FirstName__c = Patient.FirstName;
          Result.LastName__c = Patient.LastName;
          Result.MPIIID__c  = Patient.MPIID;
          Result.Prefix__c = Patient.Prefix;
          Result.Sex__c = Patient.Sex;
          Result.Telephone__c = Patient.Telephone;    
          Result.MRN__c = Patient.MRN;
          
          Results.add(Result);
      }
       
      Insert Results;
       
      Map<String,Object> result = new Map<String,Object>();
      result.put('recordCount', '0');
      return new Process.PluginResult(result); 
     
   }

   global Process.PluginDescribeResult describe() { 
      Process.PluginDescribeResult result = new Process.PluginDescribeResult(); 
      result.Name = 'Search Patient';
      result.Tag = 'Account Classes';
      result.inputParameters = new List<Process.PluginDescribeResult.InputParameter>();
      Process.PluginDescribeResult.InputParameter MPIID = new Process.PluginDescribeResult.InputParameter('MPIID', Process.PluginDescribeResult.ParameterType.STRING,false);
      Process.PluginDescribeResult.InputParameter LastName = new Process.PluginDescribeResult.InputParameter('LastName', Process.PluginDescribeResult.ParameterType.STRING,false);
      Process.PluginDescribeResult.InputParameter Telephone = new Process.PluginDescribeResult.InputParameter('Telephone', Process.PluginDescribeResult.ParameterType.STRING,false);
      result.inputParameters.add(MPIID);
      result.inputParameters.add(LastName);
      result.inputParameters.add(Telephone);
       
       
   	  result.outputParameters = new 
         List<Process.PluginDescribeResult.OutputParameter>{              
            new Process.PluginDescribeResult.OutputParameter('recordCount', 
            Process.PluginDescribeResult.ParameterType.STRING )
                }; 
      return result; 
   }
}